version: '3'
services:
  api:
    build:
      context: ./api
      args:
        API_PORT: 5000
    image: raphaelneumann/stone-challenge-api
    environment:
      - API_DB='postgres://devops:devops@localhost:5432/challenge' # An postgresql url example
  web:
    build:
      context: ./web
    image: raphaelneumann/stone-challenge-web
    ports:
      - "8080:8080"
    environment:
      - API_HOST=http://api:5000
      - PORT=8080
